//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BidSoftware.EntityFrameworkEnvironment
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostalValue
    {
        public int NumericCodeFrom { get; set; }
        public int NumericCodeTo { get; set; }
        public decimal Price { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Country Country1 { get; set; }
    }
}
