//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BidSoftware.EntityFrameworkEnvironment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int Id { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public decimal TotalValue { get; set; }
        public Nullable<decimal> CreditCard { get; set; }
        public int BidId { get; set; }
        public int CountryToShip { get; set; }
        public string Address { get; set; }
    
        public virtual Bid Bid { get; set; }
        public virtual Country Country { get; set; }
    }
}
