//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BidSoftware.EntityFrameworkEnvironment
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Bids = new HashSet<Bid>();
            this.Items = new HashSet<Item>();
            this.UserAddressHistories = new HashSet<UserAddressHistory>();
        }
    
        public string Email { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public byte[] Password { get; set; }
        public int CountryNum { get; set; }
    
        public virtual ICollection<Bid> Bids { get; set; }
        public virtual Country Country { get; set; }
        public virtual ICollection<Item> Items { get; set; }
        public virtual ICollection<UserAddressHistory> UserAddressHistories { get; set; }
    }
}
