//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BidSoftware.EntityFrameworkEnvironment
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAddressHistory
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string OldAddress { get; set; }
        public int OldCountry { get; set; }
        public System.DateTime Stamp { get; set; }
    
        public virtual User User { get; set; }
    }
}
