//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BidSoftware.EntityFrameworkEnvironment
{
    using System;
    using System.Collections.Generic;
    
    public partial class vItem
    {
        public int ItemId { get; set; }
        public string Description { get; set; }
        public int ItemConditionId { get; set; }
        public string UserEmail { get; set; }
        public Nullable<long> ROW_NR { get; set; }
    }
}
