//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BidSoftware.EntityFrameworkEnvironment
{
    using System;
    using System.Collections.Generic;
    
    public partial class vUser
    {
        public string Email { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public byte[] Password { get; set; }
        public int CountryNum { get; set; }
        public Nullable<long> ROW_NR { get; set; }
    }
}
